services:
  db-server:
    build:
      context: ./../mysql-scripts/ # use mysql folder
      dockerfile: ./../docker/db-server/Dockerfile
    restart: always
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      - '3306:3306'

  app:
    build: 
      context: ./../src/ # use this foulder as main
      dockerfile: ./../docker/app/Dockerfile # specifying the python Dockerfile dir
    command: sh -c 'sleep 5s ; python3 ./main.py'
    depends_on:
    - db-server


    # volumes: # run the sql script (optinal cause I already have a run script in Dockerfile)
    #   - ./mysql:/docker-entrypoint-initdb.d