services:
  db-server:
    build:
      context: ./../mysql-scripts/ # use mysql folder
      dockerfile: ./../docker/db-server/Dockerfile
    restart: always
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      - '3306:3306'

  app:
    build:
      context: ./../ # use this folder as main !can't use ./.. to leave this filepath
      dockerfile: ./docker/app/Dockerfile # specifying the python Dockerfile dir
    command: sh -c 'sleep 5s ; python3 ./main.py' # you can specify the --rooms-path --students-path --output-format here after the ./main.py
    depends_on:
    - db-server
